python application.py --target original/1.jpg
python application.py --target original/2.jpg
python application.py --target original/3.jpg
python application.py --target original/4.jpg
python application.py --target original/5.jpg
python application.py --target original/6.jpg
python application.py --target original/7.jpg
python application.py --target original/8.jpg
python application.py --target original/9.jpg
python application.py --target original/10.jpg
python application.py --target original/11.jpg
python application.py --target original/12.jpg
python application.py --target original/13.jpg
python application.py --target original/14.jpg
python application.py --target original/15.jpg
python application.py --target original/16.jpg
python application.py --target original/17.jpg
python application.py --target original/18.jpg
python application.py --target original/19.jpg